version: 1.0.{build}
branches:
  only:
  - master
  - develop
environment:
  NuGetApiKey:
    secure: Q2iw3AS2EBEcG4wVWDZY/ruR0Whvs50gTeCleO/uypdP7G7ajODYw030N3sOONtP
build_script:
- ps: |
    function Get-VersionInfoFromGit() {
      $versionTag = (git describe --tags --abbrev=0 2>$null)

      if($LastExitCode -eq 0) {
        $version = Parse-Version $versionTag
        $buildCounter = (git rev-list ${versionTag}..HEAD --count) + 1
      } else {
        $version = New-Object Version "0.0.0.0"
        $buildCounter = (git rev-list HEAD --count)
      }

      $result = @{
        Version = $version;
        BuildCounter = $buildCounter;
      }

      return (New-Object -TypeName PSObject -Property $result)
    }

    function Parse-Version([string] $versionTag) {
      if (-not ($versionTag -Match "^v(\d+\.\d+\.\d+)$")) {
        throw "The tag '$versionTag' is not a valid version tag of the form 'v{major}.{minor}.{patch}'."
      }

      $parsedVersion = New-Object Version $versionTag.Substring(1)

      return $parsedVersion
    }

    $VersionTag = ""

    if ($env:APPVEYOR_REPO_BRANCH -eq "master" -and $env:APPVEYOR_REPO_TAG -eq "true") {
      $Version = Parse-Version $env:APPVEYOR_REPO_TAG_NAME
      $BuildCounter = 0

      $IsPreReleaseBuild = $False
      $PushNuGetPackages = $True
    } else {
      $versionInfo = Get-VersionInfoFromGit
      $Version = $versionInfo.Version
      $BuildCounter = $versionInfo.BuildCounter
      
      $IsPreReleaseBuild = $True
      $PushNuGetPackages = $False
    }
        
    Push-Location "src"

    ./Build.ps1 `
      -Mode "AppVeyor" `
      -Version "$Version" `
      -BuildCounter $BuildCounter `
      -CommitHash "$env:APPVEYOR_REPO_COMMIT" `
      -Configuration "Release" `
      -CreateNuGetPackages $True `
      -PushNuGetPackages $PushNuGetPackages `
      -IsPreReleaseBuild $IsPreReleaseBuild `
      -NuGetApiKey "$env:NuGetApiKey"

    Pop-Location
test: off
deploy:
- provider: GitHub
  auth_token:
    secure: Lp2YKeJITl6VZV0SSdpSrbnuPujRolIyat9yAIq7W3xNkSZ36PGrPwRMrPBK4V11
  draft: true
  prerelease: true
  on:
    branch: master